run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      - name: unhandled-error
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errorlint
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - importas
    - ineffassign
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - thelper


