run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      main:
        files:
          - "!**/*_a _file.gen"
        allow:
          - $gostd
          - github.com/stretchr/testify/require
issues:
  exclude-rules:
    - path: _test\.gen
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - importas
    - ineffassign
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - thelper


