version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "calendar"
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "sa"
    ports:
      - "5432:5432"