logger:
  level: "info"
db:
  driver: "postgres"
  host: "0.0.0.0"
  port: 5432
  user: "sa"
  password: "sa"
  db: "calendar"
  appName: "Calendar"
http:
  host: "0.0.0.0"
  port: "8080"
grpc:
  port: 44044
schedule:
  interval: "10s"
broker:
  url: "0.0.0.0:5672"
  login: "admin"
  password: "555555"