name: Otus homework tests

on:
  push:
    pull_request:
      branches: [ "main" ]
env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hw12_13_14_15_calendar
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        run: |
        go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        golangci-lint run ./...

  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hw12_13_14_15_calendar
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -v -count=1 -race -timeout=1m ./...

