name: Otus homework tests

on:
  push:
    pull_request:
      branches: [ "main" ]
env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Display path
        run: |
          echo "Current directory: $PWD"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.41.1
          golangci-lint run ./...

      - name: Run tests
        run: go test -v ./...
